name: snowcast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.1.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/weather_icons/
